# Change these first
owner: undp # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: Main site
    url: https://www.undp.org
  - name: Design system
    url: https://design.undp.org
  - name: Featured stories
    url: https://feature.undp.org
  - name: Human development report
    url: https://hdr.undp.org
  - name: Jobs site
    url: https://jobs.undp.org/cj_view_jobs.cfm
  - name: Procurement notices
    url: https://procurement-notices.undp.org
  - name: Stories on exposure.co
    url: https://stories.undp.org
  - name: Transparency portal
    url: https://open.undp.org
  - name: UNDP Giving
    url: https://give.undp.org/

assignees: # Users to assign downtime issues (optional)
  - Jura

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.undp.org
  #  baseUrl: /uptime-monitor
  logoUrl: https://www.undp.org/sites/g/files/zskgke326/files/2022-04/undp-logo-blue.svg
  name: UNDP
  introTitle: "**UNDP uptime status**"
  introMessage: 
  # navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

i18n:
  footer: "[United Nations Development Programme](https://www.undp.org)"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration




